# Copyright © 2026 Brent Tunnicliff <brent@tunnicliff.dev>

# The main workflow of the project.
# Responsible for building and testing the project.

name: Pipeline

on:
  push:
    paths:
      - '**.resolved'
      - '**.swift'
      - '**.yml'
  workflow_dispatch:

permissions: {}

jobs:
  xcodebuild:
    strategy:
      # Don't cancel the other matrix values if one fails.
      fail-fast: false
      matrix:
        target: [
          { platform: "iOS", simulator_version: "26.2" },
          { platform: "tvOS", simulator_version: "26.2" },
          { platform: "watchOS", simulator_version: "26.2" },
          { platform: "visionOS", simulator_version: "26.2" },

          # macOS runs on the host and doesn't need a simulator.
          { platform: "macOS", simulator_version: "" },
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/xcodebuild.yml@v2
    with:
      platform: "${{ matrix.target.platform }}"
      runs_on: "macos-26"
      scheme: "uuid-extensions"
      simulator_version: "${{ matrix.target.simulator_version }}"
      xcode_path: "/Applications/Xcode_26.6.app"

  swift:
    strategy:
      # Don't cancel the other matrix values if one fails.
      fail-fast: false
      matrix:
        run_on: [
          "ubuntu-latest",
          "macos-latest",
          "windows-latest",
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/swift.yml@v2
    with:
      runs_on: "${{ matrix.run_on }}"

  swift_sdks:
    strategy:
      # Don't cancel the other matrix values if one fails.
      fail-fast: false
      matrix:
        platform: [
          { sdks: "android", swift_sdk: "swift-6.3-RELEASE_android" },
          { sdks: "wasm", swift_sdk: "swift-6.3-RELEASE_wasm" },
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/swift.yml@v2
    name: "swift (${{ matrix.platform.sdks }})"
    with:
      runs_on: "ubuntu-latest"
      sdks: "${{ matrix.platform.sdks }}"
      swift_sdk: "${{ matrix.platform.swift_sdk }}"
      swift_version: "6.3"

  lint:
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/lint.yml@v2
    with:
      runs_on: "macos-26"
